### ISSUE TITLE
【High】謎のバグ

### ISSUE THREAD

**Issue by corky08** [KU-onji/ene_backend#38]
（おそらくタスク完了時）時々エラーを吐く
原因不明

**Comment by corky08** [comment]
エラー文：
Traceback (most recent call last):
  File "C:\Users\kouki\ene_backend\.venv\Lib\site-packages\sqlalchemy\orm\session.py", line 3523, in delete
    state = attributes.instance_state(instance)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute '_sa_instance_state'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\kouki\ene_backend\.venv\Lib\site-packages\reflex\state.py", line 1493, in _process_event
    events = fn(**payload)
             ^^^^^^^^^^^^^
  File "C:\Users\kouki\ene_backend\ene_backend\state\chat_state.py", line 22, in answer
    self.complete_task(task)
  File "C:\Users\kouki\ene_backend\ene_backend\state\task_state.py", line 50, in complete_task
    session.delete(delete_task)
  File "C:\Users\kouki\ene_backend\.venv\Lib\site-packages\sqlalchemy\orm\session.py", line 3525, in delete
    raise exc.UnmappedInstanceError(instance) from err
sqlalchemy.orm.exc.UnmappedInstanceError: Class 'builtins.NoneType' is not mapped

**Comment by corky08** [comment]
「完了」を押す
↓
すぐにDBからタスクが消える（フロントのタスク表には残ったまま）
↓
タスク表から消える前にもう一度「完了」を押す
↓
DBから削除する処理が走るが既に無いのでエラー
